// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvrkxkpEMrM4GfZusea8t7M3V9rV4boT0',
    appId: '1:910582616970:web:3c0d0582c1cd6443386e73',
    messagingSenderId: '910582616970',
    projectId: 'habits-app-fec2f',
    authDomain: 'habits-app-fec2f.firebaseapp.com',
    storageBucket: 'habits-app-fec2f.firebasestorage.app',
    measurementId: 'G-W4S6Y4GJ15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnSz9Px3n67GIJBl5gfeQdaI03Tdpc11A',
    appId: '1:910582616970:android:d2b03511cd6c0afb386e73',
    messagingSenderId: '910582616970',
    projectId: 'habits-app-fec2f',
    storageBucket: 'habits-app-fec2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqpOYJkZuIDd4L_5Bs-fkgE_rpbTgSgcQ',
    appId: '1:910582616970:ios:1b965047360fa836386e73',
    messagingSenderId: '910582616970',
    projectId: 'habits-app-fec2f',
    storageBucket: 'habits-app-fec2f.firebasestorage.app',
    iosBundleId: 'com.example.blankTemplateTouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpQF8JOBnk9U_dQJoNgtdn3yEqr0MI24o',
    appId: '1:74833144203:web:241711befa90d5ab92678e',
    messagingSenderId: '74833144203',
    projectId: 'car-wash-app-1c48c',
    authDomain: 'car-wash-app-1c48c.firebaseapp.com',
    storageBucket: 'car-wash-app-1c48c.firebasestorage.app',
    measurementId: 'G-PGM6M52W3V',
  );
}